project:
  type: website
  output-dir: docs

website:
  
  image: "image_pratiquer"
  
  navbar:

    logo : logo_pratiquer.png
  
    left:
      - href: index.qmd
        text: Accueil
      - href: exercice.qmd
        text: Exercice
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
        
    right: 
      - icon: youtube
        href: https://youtube/PratiqueR
      - icon: github
        href: https://github.com/PratiqueR
      - icon: envelope
        href: mailto:pratiquerpro@outlook.com
        
  sidebar:
        style: "docked"
        search: true
        contents:
          - text: "Qu'est ce que R ?"
            href: pages/presentation_R.qmd
            
          - text: "Installation et Configuration"
            href: pages/installation.qmd
            
          - text: "Bonne pratiques"
            href: pages/bonne_pratique.qmd
            
            
            
          - section: "Fonctions R"
            contents:
                
              - section: "Gestions de fichiers"
                contents:
                
              - section: "Aggrégation"
                contents:
                    - pages/fonctions/agregation/somme.qmd
                    - pages/fonctions/agregation/minimum.qmd
                    - pages/fonctions/agregation/maximum.qmd
                    - pages/fonctions/agregation/moyenne.qmd
                    - pages/fonctions/agregation/mediane.qmd
                    - pages/fonctions/agregation/sd.qmd
                    - pages/fonctions/agregation/variance.qmd
                    - pages/fonctions/agregation/prod.qmd
                    - pages/fonctions/agregation/length.qmd
                    - pages/fonctions/agregation/range.qmd
                    - pages/fonctions/agregation/summary.qmd
                    - pages/fonctions/agregation/table.qmd
                    - pages/fonctions/agregation/quantile.qmd
          
              - text: "Visualisation"
                href: fonctions/visualisation.qmd
                 
              - section: "Manipulation de données"
                contents:
                    - pages/fonctions/manipulation/subset.qmd
                    - pages/fonctions/manipulation/merge.qmd
                    - pages/fonctions/manipulation/cbind.qmd
                    - pages/fonctions/manipulation/rbind.qmd
                    - pages/fonctions/manipulation/apply.qmd
                    - pages/fonctions/manipulation/lapply.qmd
                    - pages/fonctions/manipulation/sapply.qmd
                    - pages/fonctions/manipulation/tapply.qmd
                    - pages/fonctions/manipulation/sort.qmd
                    - pages/fonctions/manipulation/order.qmd
                    - pages/fonctions/manipulation/split.qmd
                    - pages/fonctions/manipulation/transform.qmd
                    - pages/fonctions/manipulation/rep.qmd
                    - pages/fonctions/manipulation/seq.qmd
       
          - section: "Statistiques"
            contents:
                  - pages/fonctions/stats/
                  - pages/fonctions/stats/
          
          - section: "Packages"
            contents: 
                    - pages/packages/introduction_packages.qmd  
          - section: "Machine Learning"
            contents:
          - section: "Deep Learning"
            contents:
          - section: "Cartographie"
            contents:
          - section: "Shiny"
            contents:
                    - pages/shiny/introduction_shiny.qmd
                    - pages/shiny/tutoriel_application.qmd
                    - pages/shiny/bslib.qmd
          - section: "Quarto"
            contents:
                    - pages/quarto/presentation_quarto.qmd
          - text: "Rmarkdown"
            href: pages/rmarkdown.qmd
          - text: "Web scraping"
            href: pages/webscraping.qmd
          - section: "API"
            contents:
          - section: "Git et Github"
            contents:


  
  page-footer: "Copyright 2025, PratiqueR" 

format:
  html:
    theme: 
          light: litera
          dark: [darkly, styles-dark.scss]
    css: styles.css
    toc: true
    page-layout: full

editor: visual

