---
title: "MEDIAN()"

lang: fr
categories:
  - aggrégation
---

La fonction **`median()`** permet de calculer la **médiane** d’un ensemble de valeurs numériques. La médiane est la valeur centrale d’un ensemble de nombres triés dans l’ordre croissant. Si le nombre d’éléments est impair, la médiane est le nombre du milieu. Si le nombre d’éléments est pair, la médiane est la moyenne des deux valeurs centrales.

## Syntaxe

L’utilisation de cette fonction est simple : il suffit d’indiquer les valeurs ou la variable dont on souhaite obtenir la médiane. Voici la syntaxe de base pour calculer la médiane d’une variable dans un data frame :

``` r
---
median(data$ma_variable)
---
```

## Exemple

### Exemple 1

Dans ce premier exemple, nous allons utiliser la fonction **`median()`** pour obtenir la valeur centrale d'un ensemble de chiffres. Il suffit de passer les nombres dans la fonction, en les séparant par des virgules. La fonction trie les valeurs et retourne la médiane.

``` r
---
median(c(1,3,5,7,9))
---
```

```{r echo=FALSE}
median(c(1,3,5,7,9))
```

### Exemple 2










