---
title: "SD()"

lang: fr
categories:
  - aggrégation
---

La fonction **`sd()`** permet de calculer l’**écart-type** d’un ensemble de valeurs numériques. L’écart-type mesure la dispersion des données autour de leur moyenne. Plus l’écart-type est élevé, plus les valeurs sont dispersées.

L’écart-type ($\sigma$ pour une population, $s$ pour un échantillon) est défini par la formule suivante :

$$
s = \sqrt{\frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2}
$$

où :

- $x_i$ représente chaque valeur de l’échantillon,  

- $\bar{x}$ est la moyenne des valeurs,  

- $n$ est le nombre total de valeurs dans l’échantillon.

## Syntaxe

La fonction prend en entrée les valeurs ou la variable dont on souhaite obtenir l’écart-type. Voici la syntaxe de base pour calculer l’écart-type d’une variable dans un data frame :

```r
sd(data$ma_variable)
```

## Exemple

Ici, utiliser la fonction **`sd()`** pour calculer l’écart-type d’une liste de chiffres. Il suffit de passer les chiffres sous forme d’un vecteur dans la fonction.

``` r
---
sd(c(5,10,2,8,3))
---
```

```{r echo=FALSE}
sd(c(5,10,2,8,3))
```

Ici, l’écart-type est 3.36, ce qui indique la dispersion des valeurs autour de leur moyenne.

