---
title: "VAR()"

lang: fr
categories:
  - aggrégation
---

La fonction **`var()`** permet de calculer la **variance** d’un ensemble de valeurs numériques. La variance mesure la dispersion des données autour de leur moyenne.

La variance ($sigma^2$ pour une population, $s^2$ pour un échantillon) est définie par la formule suivante :

$$
s^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2
$$

où :

- $x_i$ représente chaque valeur de l’échantillon,  

- $\bar{x}$ est la moyenne des valeurs,  

- $n$ est le nombre total de valeurs dans l’échantillon.  

## Syntaxe

La fonction prend en entrée les valeurs ou la variable dont on souhaite obtenir la variance. Voici la syntaxe de base pour calculer la variance d’une variable dans un data frame :

```r
var(data$ma_variable)
```

## Exemple

Ici, nous utilisons la fonction **`var()`** pour calculer la variance d’une liste de chiffres. Il suffit de passer les chiffres sous forme d’un vecteur dans la fonction.

``` r
---
var(c(6,3,8,1,4,5))
---
```

```{r echo=FALSE}
var(c(6,3,8,1,4,5))
```





