---
title: "MAX()"

lang: fr
categories:
  - aggrégation
---

La fonction **MAX()** permet de calculer la valeur maximale d’un objet numérique (vecteur, matrice, variable ...). *Max()* renvoie la plus grande valeur parmi celles présentes dans l’objet, en ignorant automatiquement les valeurs manquantes (NA) si spécifié.


Voici la page pour la fonction MAX() dans le même format :

markdown
Copy
Edit
---
title: "MAX()"
lang: fr
categories:
  - aggrégation
---

La fonction **MAX()** permet de calculer la valeur maximale d’un objet numérique (vecteur, matrice, variable ...). **Max()** renvoie la plus grande valeur parmi celles présentes dans l’objet, en ignorant automatiquement les valeurs manquantes (NA) si spécifié.

## Syntaxe

L’utilisation de cette fonction est simple, il suffit d'indiquer les valeurs ou la variable pour laquelle vous souhaitez trouver la valeur maximale. Voici la syntaxe de base pour obtenir la valeur maximale d’une variable dans un data frame, par exemple :

``` r
---
max(data$ma_variable)
---
```

## Exemple

### Exemple 1

Dans ce premier exemple, nous allons utiliser la fonction `max()` pour obtenir la valeur maximale parmi plusieurs chiffres. Il suffit de passer les nombres dans la fonction, en les séparant par des virgules. La fonction calcule ensuite la plus grande valeur parmi ces nombres.

``` r
---
max(1,2,3)
---
```

```{r echo=FALSE}
max(1,2,3)
```

### Exemple 2








