---
title: "MEAN()"

lang: fr
categories:
  - aggrégation
---

La fonction **MEAN()** permet de calculer la moyenne arithmétique des éléments d’un objet numérique (vecteur, matrice, variable ...). **Mean()** additionne les valeurs numériques et les divise par leur nombre total. Par défaut, les valeurs manquantes (`NA`) ne sont pas ignorées et renvoient un résultat `NA`.

## Syntaxe

L’utilisation de cette fonction est simple : il suffit d’indiquer les valeurs ou la variable dont on souhaite calculer la moyenne. Voici la syntaxe de base pour obtenir la moyenne d’une variable dans un data frame :

``` r
---
mean(data$ma_variable)
---
```

## Exemple

### Exemple 1

Dans ce premier exemple, nous allons utiliser la fonction `mean()` pour calculer la moyenne de plusieurs chiffres. Il suffit de passer les nombres dans la fonction, en les séparant par des virgules. La fonction calcule ensuite la moyenne de ces nombres.

``` r
---
mean(1,2,3,4,5)
---
```

```{r echo=FALSE}
mean(1,2,3,4,5)
```

### Exemple 2
