---
title: "SD()"

lang: fr
categories:
  - aggrégation
---

La fonction **SD()** permet de calculer l’écart-type d’un ensemble de valeurs numériques. L’écart-type mesure la dispersion des données autour de leur moyenne. Plus l’écart-type est élevé, plus les valeurs sont dispersées.

L’écart-type ($\sigma$ pour une population, $s$ pour un échantillon) est défini par la formule suivante :

$$
s = \sqrt{\frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2}
$$

où :

- $x_i$ représente chaque valeur de l’échantillon,  

- $\bar{x}$ est la moyenne des valeurs,  

- $n$ est le nombre total de valeurs dans l’échantillon.

## Syntaxe

L’utilisation de cette fonction est simple : il suffit d’indiquer les valeurs ou la variable dont on souhaite obtenir l’écart-type. Voici la syntaxe de base pour calculer l’écart-type d’une variable dans un data frame :

```r
sd(data$ma_variable)
```

## Exemple

### Exemple 1

Dans ce premier exemple, nous allons utiliser la fonction `sd()` pour calculer l’écart-type d’un ensemble de chiffres. Il suffit de passer les nombres sous forme d’un vecteur dans la fonction.

``` r
---
sd(c(1,2,3,4,5))
---
```

```{r echo=FALSE}
sd(c(1,2,3,4,5))
```

Ici, l’écart-type est 1.58, ce qui indique la dispersion des valeurs autour de leur moyenne.

### Exemple 2

